// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_iOG0wZwryUeGYHRhBz3riZsdGQd6eu8',
    appId: '1:724770420804:web:f53ad0b0896b05a8fbe411',
    messagingSenderId: '724770420804',
    projectId: 'cairo-government',
    authDomain: 'cairo-government.firebaseapp.com',
    storageBucket: 'cairo-government.firebasestorage.app',
    measurementId: 'G-BD5YMH53P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCrJHQwsBLEQalTmeINCitw79xYEhjeNQ',
    appId: '1:724770420804:android:68b151fd4bf26ff8fbe411',
    messagingSenderId: '724770420804',
    projectId: 'cairo-government',
    storageBucket: 'cairo-government.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_iOG0wZwryUeGYHRhBz3riZsdGQd6eu8',
    appId: '1:724770420804:web:544ad90e78e26e93fbe411',
    messagingSenderId: '724770420804',
    projectId: 'cairo-government',
    authDomain: 'cairo-government.firebaseapp.com',
    storageBucket: 'cairo-government.firebasestorage.app',
    measurementId: 'G-Y0M5VB7MTW',
  );

}